name: First Workflow

on:
  push: 
    branches: [main]
  workflow_dispatch:   #runs the workflow manually


jobs:
  basic-demo:
    runs-on:  ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: list files
        run: |
          ls -la
          ls -ltrh
          pwd
          lsblk
          df -h
          if-config