name: First Workflow

on:
  push: 
    branches: [main]
  workflow_dispatch:   #runs the workflow manually


jobs:
  basic-demo:
    runs-on:  ubuntu-latest

    steps:
      - name: sayhello
        run: echo "Hi this is harsha"

      - name: username
        run: uname -a

      - name: list-ct-dir
        run: pwd

      - name: list-disk-space
        run: df -h      